base_url = "https://januson.github.io"
title = ""
description = "Ondrej Janus blog"
default_language = "en"

paginate_by = 10
build_search_index = true
compile_sass = true
highlight_code = true
highlight_theme = "cheerfully-light"

taxonomies = [
    {name = "tags", rss = true},
]

[extra]
menu = [
    {url = "$BASE_URL", name = "Blog"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]