version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    environment:
      - ZOLA: https://github.com/getzola/zola/releases/download/v0.6.0/zola-v0.6.0-x86_64-unknown-linux-gnu.tar.gz
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Zola static site generator
          command: curl -s -L $ZOLA | sudo tar xvzf - -C /usr/local/bin
      - run:
          name: Build site
          command: zola build
      - run:
          name: Copy circleci config
          command: cp -r .circleci ./public
      - persist_to_workspace:
          root: public
          paths:
            - "*"
            - ".circleci/*"
            - ".nojekyll"
  deploy:
    docker:
      - image: circleci/rust:latest
    working_directory: ~/checkout
    steps:
      - checkout
      - run:
          name: Prepare release branch
          command: |
            git branch -D master
            git checkout --orphan master
            git rm -rf .
            git clean -fxd
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "0b:30:24:11:f4:f9:fc:a4:51:50:47:e8:41:16:a1:49"
      - deploy:
          name: Deploy release
          command: |
            git config --global user.email $USER_EMAIL
            git config --global user.name $USER_NAME
            echo "Commit and push..."
            git add -fA
            git status
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push origin master --force
            echo "Deployed successfully!"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
