version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    environment:
      - ZOLA: https://github.com/getzola/zola/releases/download/v0.12.2/zola-v0.12.2-x86_64-unknown-linux-gnu.tar.gz
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Zola static site generator
          command: curl -s -L $ZOLA | sudo tar xvzf - -C /usr/local/bin
      - run:
          name: Build site
          command: zola build
      - run:
          name: Copy circleci config
          command: cp -r .circleci ./public
      - persist_to_workspace:
          root: public
          paths:
            - "*"
            - ".circleci/*"
            - ".nojekyll"
  deploy:
    docker:
      - image: circleci/rust:latest
    environment:
      - TARGET_BRANCH: gh-pages
    working_directory: ~/checkout
    steps:
      - checkout
      - run:
          name: Setup Git user
          command: bash ./.circleci/setup_user.sh $USER_EMAIL $USER_NAME
      - run:
          name: Prepare release branch
          command: bash ./.circleci/nuke_branch.sh $TARGET_BRANCH
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "0b:30:24:11:f4:f9:fc:a4:51:50:47:e8:41:16:a1:49"
      - deploy:
          name: Deploy release
          command: bash ./.circleci/deploy.sh $TARGET_BRANCH $CIRCLE_SHA1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
